### ISSUE TITLE
Edit custom board - display issue's title with a link to the issue

### ISSUE THREAD

**Issue by shaal** [mglaman/contribkanban.com#155] opened 2019-05-14 16:44 UTC
When editing a custom board, it would be very helpful after typing the issue number (maybe after leaving that box) that conribkanban would display next to the issue number the title of the issue with a link to the issue itself.

It will help a lot knowing what's going on in the edit page. Otherwise, it's just a list of numbers.

![image](https://user-images.githubusercontent.com/22901/57715898-be5b8280-7645-11e9-8d86-aae59e5244c5.png)

**Comment by mglaman** [comment] 2019-06-08 03:41
I'm going to close this as a duplicate of #150, which I opened earlier.

**Closed by mglaman** 2019-06-08 03:41 UTC
